//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetWay.BISAService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", ConfigurationName="BISAService.aqua")]
    public interface aqua {
        
        // CODEGEN: Generating message contract since the operation purchasePOSATC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetWay.BISAService.purchasePOSATCResponse1 purchasePOSATC(GetWay.BISAService.purchasePOSATCRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<GetWay.BISAService.purchasePOSATCResponse1> purchasePOSATCAsync(GetWay.BISAService.purchasePOSATCRequest1 request);
        
        // CODEGEN: Generating message contract since the operation cancelOrQuestPOSATC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetWay.BISAService.cancelOrQuestPOSATCResponse1 cancelOrQuestPOSATC(GetWay.BISAService.cancelOrQuestPOSATCRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<GetWay.BISAService.cancelOrQuestPOSATCResponse1> cancelOrQuestPOSATCAsync(GetWay.BISAService.cancelOrQuestPOSATCRequest1 request);
        
        // CODEGEN: Generating message contract since the operation version is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GetWay.BISAService.versionResponse1 version(GetWay.BISAService.versionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<GetWay.BISAService.versionResponse1> versionAsync(GetWay.BISAService.versionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public partial class purchasePOSATCRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNumberField;
        
        private string movilNumberField;
        
        private string smsPINField;
        
        private decimal amountField;
        
        private string currencyField;
        
        private string commerceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string movilNumber {
            get {
                return this.movilNumberField;
            }
            set {
                this.movilNumberField = value;
                this.RaisePropertyChanged("movilNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string smsPIN {
            get {
                return this.smsPINField;
            }
            set {
                this.smsPINField = value;
                this.RaisePropertyChanged("smsPIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string commerce {
            get {
                return this.commerceField;
            }
            set {
                this.commerceField = value;
                this.RaisePropertyChanged("commerce");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public partial class purchasePOSATCResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNumberField;
        
        private string cardNumberField;
        
        private System.DateTime expirationField;
        
        private bool expirationFieldSpecified;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("cardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
                this.RaisePropertyChanged("expiration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationSpecified {
            get {
                return this.expirationFieldSpecified;
            }
            set {
                this.expirationFieldSpecified = value;
                this.RaisePropertyChanged("expirationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class purchasePOSATCRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", Order=0)]
        public GetWay.BISAService.purchasePOSATCRequest purchasePOSATCRequest;
        
        public purchasePOSATCRequest1() {
        }
        
        public purchasePOSATCRequest1(GetWay.BISAService.purchasePOSATCRequest purchasePOSATCRequest) {
            this.purchasePOSATCRequest = purchasePOSATCRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class purchasePOSATCResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", Order=0)]
        public GetWay.BISAService.purchasePOSATCResponse purchasePOSATCResponse;
        
        public purchasePOSATCResponse1() {
        }
        
        public purchasePOSATCResponse1(GetWay.BISAService.purchasePOSATCResponse purchasePOSATCResponse) {
            this.purchasePOSATCResponse = purchasePOSATCResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public partial class cancelOrQuestPOSATCRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNumberField;
        
        private cancelOrQuestPOSATCRequestCause causeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public cancelOrQuestPOSATCRequestCause cause {
            get {
                return this.causeField;
            }
            set {
                this.causeField = value;
                this.RaisePropertyChanged("cause");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public enum cancelOrQuestPOSATCRequestCause {
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        Q,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://aqua.bisa.com/servicios/pos/atc/ws")]
    public partial class cancelOrQuestPOSATCResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string referenceNumberField;
        
        private string cardNumberField;
        
        private System.DateTime expirationField;
        
        private bool expirationFieldSpecified;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("cardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
                this.RaisePropertyChanged("expiration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expirationSpecified {
            get {
                return this.expirationFieldSpecified;
            }
            set {
                this.expirationFieldSpecified = value;
                this.RaisePropertyChanged("expirationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelOrQuestPOSATCRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", Order=0)]
        public GetWay.BISAService.cancelOrQuestPOSATCRequest cancelOrQuestPOSATCRequest;
        
        public cancelOrQuestPOSATCRequest1() {
        }
        
        public cancelOrQuestPOSATCRequest1(GetWay.BISAService.cancelOrQuestPOSATCRequest cancelOrQuestPOSATCRequest) {
            this.cancelOrQuestPOSATCRequest = cancelOrQuestPOSATCRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelOrQuestPOSATCResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://aqua.bisa.com/servicios/pos/atc/ws", Order=0)]
        public GetWay.BISAService.cancelOrQuestPOSATCResponse cancelOrQuestPOSATCResponse;
        
        public cancelOrQuestPOSATCResponse1() {
        }
        
        public cancelOrQuestPOSATCResponse1(GetWay.BISAService.cancelOrQuestPOSATCResponse cancelOrQuestPOSATCResponse) {
            this.cancelOrQuestPOSATCResponse = cancelOrQuestPOSATCResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.bisa.com/schema/aqua/version")]
    public partial class versionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="versionRequest", Namespace="http://xml.bisa.com/schema/aqua/version", Order=0)]
        public object versionRequest1;
        
        public versionRequest() {
        }
        
        public versionRequest(object versionRequest1) {
            this.versionRequest1 = versionRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xml.bisa.com/schema/aqua/version", Order=0)]
        public GetWay.BISAService.versionResponse versionResponse;
        
        public versionResponse1() {
        }
        
        public versionResponse1(GetWay.BISAService.versionResponse versionResponse) {
            this.versionResponse = versionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface aquaChannel : GetWay.BISAService.aqua, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class aquaClient : System.ServiceModel.ClientBase<GetWay.BISAService.aqua>, GetWay.BISAService.aqua {
        
        public aquaClient() {
        }
        
        public aquaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public aquaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public aquaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public aquaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetWay.BISAService.purchasePOSATCResponse1 GetWay.BISAService.aqua.purchasePOSATC(GetWay.BISAService.purchasePOSATCRequest1 request) {
            return base.Channel.purchasePOSATC(request);
        }
        
        public GetWay.BISAService.purchasePOSATCResponse purchasePOSATC(GetWay.BISAService.purchasePOSATCRequest purchasePOSATCRequest) {
            GetWay.BISAService.purchasePOSATCRequest1 inValue = new GetWay.BISAService.purchasePOSATCRequest1();
            inValue.purchasePOSATCRequest = purchasePOSATCRequest;
            GetWay.BISAService.purchasePOSATCResponse1 retVal = ((GetWay.BISAService.aqua)(this)).purchasePOSATC(inValue);
            return retVal.purchasePOSATCResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetWay.BISAService.purchasePOSATCResponse1> GetWay.BISAService.aqua.purchasePOSATCAsync(GetWay.BISAService.purchasePOSATCRequest1 request) {
            return base.Channel.purchasePOSATCAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetWay.BISAService.purchasePOSATCResponse1> purchasePOSATCAsync(GetWay.BISAService.purchasePOSATCRequest purchasePOSATCRequest) {
            GetWay.BISAService.purchasePOSATCRequest1 inValue = new GetWay.BISAService.purchasePOSATCRequest1();
            inValue.purchasePOSATCRequest = purchasePOSATCRequest;
            return ((GetWay.BISAService.aqua)(this)).purchasePOSATCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetWay.BISAService.cancelOrQuestPOSATCResponse1 GetWay.BISAService.aqua.cancelOrQuestPOSATC(GetWay.BISAService.cancelOrQuestPOSATCRequest1 request) {
            return base.Channel.cancelOrQuestPOSATC(request);
        }
        
        public GetWay.BISAService.cancelOrQuestPOSATCResponse cancelOrQuestPOSATC(GetWay.BISAService.cancelOrQuestPOSATCRequest cancelOrQuestPOSATCRequest) {
            GetWay.BISAService.cancelOrQuestPOSATCRequest1 inValue = new GetWay.BISAService.cancelOrQuestPOSATCRequest1();
            inValue.cancelOrQuestPOSATCRequest = cancelOrQuestPOSATCRequest;
            GetWay.BISAService.cancelOrQuestPOSATCResponse1 retVal = ((GetWay.BISAService.aqua)(this)).cancelOrQuestPOSATC(inValue);
            return retVal.cancelOrQuestPOSATCResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetWay.BISAService.cancelOrQuestPOSATCResponse1> GetWay.BISAService.aqua.cancelOrQuestPOSATCAsync(GetWay.BISAService.cancelOrQuestPOSATCRequest1 request) {
            return base.Channel.cancelOrQuestPOSATCAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetWay.BISAService.cancelOrQuestPOSATCResponse1> cancelOrQuestPOSATCAsync(GetWay.BISAService.cancelOrQuestPOSATCRequest cancelOrQuestPOSATCRequest) {
            GetWay.BISAService.cancelOrQuestPOSATCRequest1 inValue = new GetWay.BISAService.cancelOrQuestPOSATCRequest1();
            inValue.cancelOrQuestPOSATCRequest = cancelOrQuestPOSATCRequest;
            return ((GetWay.BISAService.aqua)(this)).cancelOrQuestPOSATCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetWay.BISAService.versionResponse1 GetWay.BISAService.aqua.version(GetWay.BISAService.versionRequest request) {
            return base.Channel.version(request);
        }
        
        public GetWay.BISAService.versionResponse version(object versionRequest1) {
            GetWay.BISAService.versionRequest inValue = new GetWay.BISAService.versionRequest();
            inValue.versionRequest1 = versionRequest1;
            GetWay.BISAService.versionResponse1 retVal = ((GetWay.BISAService.aqua)(this)).version(inValue);
            return retVal.versionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetWay.BISAService.versionResponse1> GetWay.BISAService.aqua.versionAsync(GetWay.BISAService.versionRequest request) {
            return base.Channel.versionAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetWay.BISAService.versionResponse1> versionAsync(object versionRequest1) {
            GetWay.BISAService.versionRequest inValue = new GetWay.BISAService.versionRequest();
            inValue.versionRequest1 = versionRequest1;
            return ((GetWay.BISAService.aqua)(this)).versionAsync(inValue);
        }
    }
}
